services:
  postgres:
    image: postgres:18
    container_name: smart-class-postgres
    restart: always
    environment:
      POSTGRES_DB: smartclassdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - smartclass-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smart-class-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartclass.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - smartclass-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  smartclass-network:
    driver: bridge
